let data = {
  members: [
    {
      id: "1",
      email: "dummy@gmail.com",
      memberType: "Medical",
      memberSubType: "Annual",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      firstName: "John",
      lastName: "Hopkins",
      primaryDegree: "BDS",
      username: "john@123",
      primarySpecilty: "Aerospace Medicine",
      createdAt: "02/07/2019",
      status: "active",
      educationDetails: [
        {
          degree: "MS",
          medicalSchoolName: "Goa Medical College",
          startYear: "2005",
          endYear: "2009",
        },
        {
          degree: "MDH",
          medicalSchoolName: "Kurnool Medical College",
          startYear: "1996",
          endYear: "2001",
        },
        {
          degree: "MPS",
          medicalSchoolName: "International Unviersity of health & Science",
          startYear: "2013",
          endYear: "2018",
        },
      ],
      phoneDetails: [
        {
          phoneType: "Cell",
          phoneNumber: "7895462154",
          extension: "+1",
        },
        {
          phoneType: "Fax",
          phoneNumber: "4856462154",
          extension: "+1",
        },
        {
          phoneType: "Home",
          phoneNumber: "4487545645",
          extension: "+1",
        },
        {
          phoneType: "Office",
          phoneNumber: "9856462154",
          extension: "+1",
        },
      ],
      addressDetails: [
        {
          addressType: "Office",
          city: "New York",
          state: "northeastern U.S",
          zipCode: "10001",
          country: "United States",
          isPrimary: true,
        },
        {
          addressType: "Home",
          city: "Los Angeles",
          state: "California",
          zipCode: "18974",
          country: "United States",
          isPrimary: false,
        },
        {
          addressType: "Mailing",
          city: "Chicago",
          state: "Illinois",
          zipCode: "45218",
          country: "United States",
          isPrimary: false,
        },
      ],
    },

    {
      id: "2",
      email: "dummy2@gmail.com",
      memberType: "Medical",
      memberSubType: "Annual",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      firstName: "John",
      lastName: "Hopkins",
      primaryDegree: "BDS",
      username: "john@123",
      primarySpecilty: "Aerospace Medicine",
      createdAt: "02/07/2019",
      status: "active",
      educationDetails: [
        {
          degree: "MS",
          medicalSchoolName: "Goa Medical College",
          startYear: "2005",
          endYear: "2009",
        },
        {
          degree: "MDH",
          medicalSchoolName: "Kurnool Medical College",
          startYear: "1996",
          endYear: "2001",
        },
        {
          degree: "MPS",
          medicalSchoolName: "International Unviersity of health & Science",
          startYear: "2013",
          endYear: "2018",
        },
      ],
      phoneDetails: [
        {
          phoneType: "Cell",
          phoneNumber: "7895462154",
          extension: "+1",
        },
        {
          phoneType: "Fax",
          phoneNumber: "4856462154",
          extension: "+1",
        },
        {
          phoneType: "Home",
          phoneNumber: "4487545645",
          extension: "+1",
        },
        {
          phoneType: "Office",
          phoneNumber: "9856462154",
          extension: "+1",
        },
      ],
      addressDetails: [
        {
          addressType: "Office",
          city: "New York",
          state: "northeastern U.S",
          zipCode: "10001",
          country: "United States",
          isPrimary: true,
        },
        {
          addressType: "Home",
          city: "Los Angeles",
          state: "California",
          zipCode: "18974",
          country: "United States",
          isPrimary: false,
        },
        {
          addressType: "Mailing",
          city: "Chicago",
          state: "Illinois",
          zipCode: "45218",
          country: "United States",
          isPrimary: false,
        },
      ],
    },

    {
      id: "3",
      email: "dummy@gmail.com",
      memberType: "Medical",
      memberSubType: "Annual",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      firstName: "John",
      lastName: "Hopkins",
      primaryDegree: "BDS",
      username: "john@123",
      primarySpecilty: "Aerospace Medicine",
      createdAt: "02/07/2019",
      status: "active",
      educationDetails: [
        {
          degree: "MS",
          medicalSchoolName: "Goa Medical College",
          startYear: "2005",
          endYear: "2009",
        },
        {
          degree: "MDH",
          medicalSchoolName: "Kurnool Medical College",
          startYear: "1996",
          endYear: "2001",
        },
        {
          degree: "MPS",
          medicalSchoolName: "International Unviersity of health & Science",
          startYear: "2013",
          endYear: "2018",
        },
      ],
      phoneDetails: [
        {
          phoneType: "Cell",
          phoneNumber: "7895462154",
          extension: "+1",
        },
        {
          phoneType: "Fax",
          phoneNumber: "4856462154",
          extension: "+1",
        },
        {
          phoneType: "Home",
          phoneNumber: "4487545645",
          extension: "+1",
        },
        {
          phoneType: "Office",
          phoneNumber: "9856462154",
          extension: "+1",
        },
      ],
      addressDetails: [
        {
          addressType: "Office",
          city: "New York",
          state: "northeastern U.S",
          zipCode: "10001",
          country: "United States",
          isPrimary: true,
        },
        {
          addressType: "Home",
          city: "Los Angeles",
          state: "California",
          zipCode: "18974",
          country: "United States",
          isPrimary: false,
        },
        {
          addressType: "Mailing",
          city: "Chicago",
          state: "Illinois",
          zipCode: "45218",
          country: "United States",
          isPrimary: false,
        },
      ],
    },

    {
      id: "4",
      email: "dummy@gmail.com",
      memberType: "Medical",
      memberSubType: "Annual",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      firstName: "John",
      lastName: "Hopkins",
      primaryDegree: "BDS",
      username: "john@123",
      primarySpecilty: "Aerospace Medicine",
      createdAt: "02/07/2019",
      status: "active",
      educationDetails: [
        {
          degree: "MS",
          medicalSchoolName: "Goa Medical College",
          startYear: "2005",
          endYear: "2009",
        },
        {
          degree: "MDH",
          medicalSchoolName: "Kurnool Medical College",
          startYear: "1996",
          endYear: "2001",
        },
        {
          degree: "MPS",
          medicalSchoolName: "International Unviersity of health & Science",
          startYear: "2013",
          endYear: "2018",
        },
      ],
      phoneDetails: [
        {
          phoneType: "Cell",
          phoneNumber: "7895462154",
          extension: "+1",
        },
        {
          phoneType: "Fax",
          phoneNumber: "4856462154",
          extension: "+1",
        },
        {
          phoneType: "Home",
          phoneNumber: "4487545645",
          extension: "+1",
        },
        {
          phoneType: "Office",
          phoneNumber: "9856462154",
          extension: "+1",
        },
      ],
      addressDetails: [
        {
          addressType: "Office",
          city: "New York",
          state: "northeastern U.S",
          zipCode: "10001",
          country: "United States",
          isPrimary: true,
        },
        {
          addressType: "Home",
          city: "Los Angeles",
          state: "California",
          zipCode: "18974",
          country: "United States",
          isPrimary: false,
        },
        {
          addressType: "Mailing",
          city: "Chicago",
          state: "Illinois",
          zipCode: "45218",
          country: "United States",
          isPrimary: false,
        },
      ],
    },

    {
      id: "5",
      email: "dummy@gmail.com",
      memberType: "Medical",
      memberSubType: "Annual",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      firstName: "John",
      lastName: "Hopkins",
      primaryDegree: "BDS",
      username: "john@123",
      primarySpecilty: "Aerospace Medicine",
      createdAt: "02/07/2019",
      status: "active",
      educationDetails: [
        {
          degree: "MS",
          medicalSchoolName: "Goa Medical College",
          startYear: "2005",
          endYear: "2009",
        },
        {
          degree: "MDH",
          medicalSchoolName: "Kurnool Medical College",
          startYear: "1996",
          endYear: "2001",
        },
        {
          degree: "MPS",
          medicalSchoolName: "International Unviersity of health & Science",
          startYear: "2013",
          endYear: "2018",
        },
      ],
      phoneDetails: [
        {
          phoneType: "Cell",
          phoneNumber: "7895462154",
          extension: "+1",
        },
        {
          phoneType: "Fax",
          phoneNumber: "4856462154",
          extension: "+1",
        },
        {
          phoneType: "Home",
          phoneNumber: "4487545645",
          extension: "+1",
        },
        {
          phoneType: "Office",
          phoneNumber: "9856462154",
          extension: "+1",
        },
      ],
      addressDetails: [
        {
          addressType: "Office",
          city: "New York",
          state: "northeastern U.S",
          zipCode: "10001",
          country: "United States",
          isPrimary: true,
        },
        {
          addressType: "Home",
          city: "Los Angeles",
          state: "California",
          zipCode: "18974",
          country: "United States",
          isPrimary: false,
        },
        {
          addressType: "Mailing",
          city: "Chicago",
          state: "Illinois",
          zipCode: "45218",
          country: "United States",
          isPrimary: false,
        },
      ],
    },
  ],
  admins: [
    {
      id: "1",
      email: "admin1@gmail.com",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      username: "john@123",
      createdAt: "02/07/2019",
      status: "active",
    },
    {
      id: "2",
      email: "admin2@gmail.com",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      username: "asern@123",
      createdAt: "02/07/2019",
      status: "active",
    },
    {
      id: "3",
      email: "admin3@gmail.com",
      currentSignIn: "06/04/2022",
      signInCount: "5",
      username: "fgth@123",
      createdAt: "02/07/2019",
      status: "active",
    },
  ],
  transactions: [
    {
      transactionId: "#1as54",
      memberName: "dummy@gmail.com",
      transactionDate: "02/07/2019",
      memberType: "dummy",
      memberSubType: "dummySub",
      amount: "4000",
    },
    {
      transactionId: "#1a5s54",
      memberName: "dummy@gmail.com",
      transactionDate: "02/07/2019",
      memberType: "dummy",
      memberSubType: "dummySub",
      amount: "4000",
    },
    {
      transactionId: "#1s54",
      memberName: "dummy@gmail.com",
      transactionDate: "02/07/2019",
      memberType: "dummy",
      memberSubType: "dummySub",
      amount: "4000",
    },
    {
      transactionId: "#1as5",
      memberName: "dummy@gmail.com",
      transactionDate: "02/07/2019",
      memberType: "dummy",
      memberSubType: "dummySub",
      amount: "4000",
    },
    {
      transactionId: "#1as4",
      memberName: "dummy@gmail.com",
      transactionDate: "02/07/2019",
      memberType: "dummy",
      memberSubType: "dummySub",
      amount: "4000",
    },
    {
      transactionId: "#1s54",
      memberName: "dummy@gmail.com",
      transactionDate: "06/07/2022",
      memberType: "dummy",
      memberSubType: "dummySub",
      amount: "4000",
    },
  ],
};

export default data;
